# Generated by Django 5.0.14 on 2026-07-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0030_seed_whitegoods_appliance_laundry'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='preferred_date_end',
            field=models.DateField(blank=True, help_text='Set together with preferred_date to describe a date range instead of a single date.', null=True),
        ),
    ]
