# Generated by Django 5.0.14 on 2026-07-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0031_task_preferred_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='market_fee_rate',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Platform fee percentage applied to Market listing sales (e.g. 2 for 2%) — separate from the job/task success fee rate.', max_digits=5),
        ),
    ]
