# Generated by Django 5.0.14 on 2026-08-08 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0033_seed_massage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_hire', models.BooleanField(default=True)),
                ('can_offer_services', models.BooleanField(default=False)),
                ('can_manage_businesses', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Capability',
                'verbose_name_plural': 'User Capabilities',
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_type', models.CharField(choices=[('client', 'Hire Someone'), ('individual_provider', 'Find Work'), ('business', 'Manage Business')], db_index=True, max_length=30)),
                ('display_name', models.CharField(max_length=160)),
                ('slug', models.SlugField(editable=False, max_length=220, unique=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='workspace_profiles/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
                'ordering': ['owner_id', 'workspace_type'],
            },
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('trading_name', models.CharField(max_length=200)),
                ('business_description', models.TextField(blank=True)),
                ('business_phone', models.CharField(blank=True, max_length=30)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('service_radius_km', models.PositiveIntegerField(default=10)),
                ('tin', models.CharField(blank=True, max_length=50, verbose_name='TIN')),
                ('fiji_business_registration_number', models.CharField(blank=True, max_length=100, verbose_name='Fiji business registration number')),
                ('fiji_trade_licence_number', models.CharField(blank=True, max_length=100, verbose_name='Fiji trade or professional licence number')),
                ('facebook_page_url', models.URLField(blank=True)),
                ('facebook_page_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('verification_status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='not_submitted', max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to='marketplace.workspace')),
            ],
            options={
                'verbose_name': 'Business Profile',
                'verbose_name_plural': 'Business Profiles',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='provider_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='marketplace.workspace'),
        ),
        migrations.AddField(
            model_name='platformfee',
            name='provider_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='platform_fees', to='marketplace.workspace'),
        ),
        migrations.AddField(
            model_name='privatereview',
            name='reviewed_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='private_reviews_received', to='marketplace.workspace'),
        ),
        migrations.AddField(
            model_name='privatereview',
            name='reviewer_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='private_reviews_written', to='marketplace.workspace'),
        ),
        migrations.AddField(
            model_name='publicreview',
            name='reviewed_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='public_reviews_received', to='marketplace.workspace'),
        ),
        migrations.AddField(
            model_name='publicreview',
            name='reviewer_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='public_reviews_written', to='marketplace.workspace'),
        ),
        migrations.AddField(
            model_name='quote',
            name='provider_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_quotes', to='marketplace.workspace'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_provider_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to='marketplace.workspace'),
        ),
        migrations.AddField(
            model_name='task',
            name='client_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_tasks', to='marketplace.workspace'),
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('staff', 'Staff')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='marketplace.workspace')),
            ],
            options={
                'verbose_name': 'Workspace Membership',
                'verbose_name_plural': 'Workspace Memberships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace_type', 'client')), fields=('owner', 'workspace_type'), name='unique_client_workspace_per_user'),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace_type', 'individual_provider')), fields=('owner', 'workspace_type'), name='unique_individual_provider_workspace_per_user'),
        ),
        migrations.AddConstraint(
            model_name='workspacemembership',
            constraint=models.UniqueConstraint(fields=('workspace', 'user'), name='unique_workspace_membership'),
        ),
    ]
