# Generated by Django 5.0.14 on 2026-08-09 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0036_backfill_workspace_fks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['workspace_type', 'display_name'], 'verbose_name': 'Workspace', 'verbose_name_plural': 'Workspaces'},
        ),
    ]
