# Generated by Django 5.0.14 on 2026-08-17 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0037_workspace_admin_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialDataDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_user_id_hash', models.CharField(max_length=128)),
                ('confirmation_code', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('not_found', 'No matching identity found')], default='pending', max_length=30)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_data_deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Data Deletion Request',
                'verbose_name_plural': 'Social Data Deletion Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('facebook', 'Facebook')], max_length=30)),
                ('provider_user_id', models.CharField(max_length=255)),
                ('email_at_link_time', models.EmailField(blank=True, max_length=254)),
                ('display_name_at_link_time', models.CharField(blank=True, max_length=255)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Identity',
                'verbose_name_plural': 'Social Identities',
            },
        ),
        migrations.AddConstraint(
            model_name='socialidentity',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='unique_social_provider_identity'),
        ),
    ]
