# Generated by Django 5.0.14 on 2026-08-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0040_message_read_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_tester',
            field=models.BooleanField(default=False, verbose_name='Beta tester (can preview unlaunched features)'),
        ),
    ]
