# Generated by Django 5.0.14 on 2026-08-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0041_user_is_tester'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='edit_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliermessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliermessage',
            name='edit_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='suppliermessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
