# Generated by Django 5.0.14 on 2026-08-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0042_message_edit_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotingappointment',
            name='alternative_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotingappointmentslot',
            name='proposed_by',
            field=models.CharField(choices=[('provider', 'Provider'), ('client', 'Client')], default='provider', max_length=10),
        ),
        migrations.AlterField(
            model_name='quotingappointment',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('alternative_proposed', 'Alternative times proposed'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], default='requested', max_length=20),
        ),
    ]
