# Generated by Django 5.0.14 on 2026-08-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0044_account_deletion_reporting_blocking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Blank means the client marked this negotiable — see budget_display / budget_type.', max_digits=10, null=True),
        ),
    ]
