# Generated by Django 5.0.14 on 2026-08-20 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0049_workspace_admin_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Linked Account',
                'verbose_name_plural': 'Linked Accounts',
            },
        ),
        migrations.AlterField(
            model_name='workspace',
            name='workspace_type',
            field=models.CharField(choices=[('client', 'Hire Someone'), ('individual_provider', 'Find Work'), ('supplier', 'Sell Supplies'), ('business', 'Manage Business')], db_index=True, max_length=30),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace_type', 'supplier')), fields=('owner', 'workspace_type'), name='unique_supplier_workspace_per_user'),
        ),
        migrations.AddField(
            model_name='linkedaccount',
            name='user_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='linkedaccount',
            name='user_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='linkedaccount',
            constraint=models.UniqueConstraint(fields=('user_a', 'user_b'), name='unique_linked_account_pair'),
        ),
    ]
