# Generated by Django 5.0.14 on 2026-08-26 23:32

from django.db import migrations, models


def bump_active_terms_version(apps, schema_editor):
    """The Acceptable Use Policy added in Terms v1.1 is a material change,
    so the live active row's terms_version needs to move off '1.0' — new
    TermsAcceptance rows are stamped from this, not from the model default."""
    PlatformSettings = apps.get_model('marketplace', 'PlatformSettings')
    PlatformSettings.objects.filter(active=True, terms_version='1.0').update(terms_version='1.1')


def revert_active_terms_version(apps, schema_editor):
    PlatformSettings = apps.get_model('marketplace', 'PlatformSettings')
    PlatformSettings.objects.filter(active=True, terms_version='1.1').update(terms_version='1.0')


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0050_linked_accounts_and_supplier_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='terms_version',
            field=models.CharField(default='1.1', help_text='Active terms version presented to users at registration', max_length=20),
        ),
        migrations.RunPython(bump_active_terms_version, revert_active_terms_version),
    ]
