# Generated by Django 5.0.14 on 2026-08-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0051_alter_platformsettings_terms_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentreport',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='acknowledged_minor_client',
            field=models.BooleanField(default=False, verbose_name='Acknowledged client is under 18'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='guardian_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='guardian_consent_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='guardian_contact',
            field=models.CharField(blank=True, help_text='Parent/guardian phone or email', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='contentreport',
            name='reason',
            field=models.CharField(choices=[('child_safety', 'Child safety concern'), ('spam', 'Spam or scam'), ('harassment', 'Harassment or abuse'), ('inappropriate', 'Inappropriate content'), ('fraud', 'Fraud or misrepresentation'), ('other', 'Other')], max_length=20),
        ),
    ]
