# Generated by Django 5.0.14 on 2026-08-27 00:19

from django.db import migrations, models


def bump_active_terms_version(apps, schema_editor):
    """Terms v1.2 (16-17 audience support, Terms §2/§13) is a material
    change — move the live active row off '1.1' so new TermsAcceptance
    rows are stamped correctly. Mirrors 0051's bump from 1.0 to 1.1."""
    PlatformSettings = apps.get_model('marketplace', 'PlatformSettings')
    PlatformSettings.objects.filter(active=True, terms_version='1.1').update(terms_version='1.2')


def revert_active_terms_version(apps, schema_editor):
    PlatformSettings = apps.get_model('marketplace', 'PlatformSettings')
    PlatformSettings.objects.filter(active=True, terms_version='1.2').update(terms_version='1.1')


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0052_contentreport_escalated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='terms_version',
            field=models.CharField(default='1.2', help_text='Active terms version presented to users at registration', max_length=20),
        ),
        migrations.RunPython(bump_active_terms_version, revert_active_terms_version),
    ]
