# Generated by Django 5.0.14 on 2026-08-27 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0053_alter_platformsettings_terms_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(blank=True, max_length=200)),
                ('town', models.CharField(blank=True, max_length=50)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.tradecategory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['matched_trade', 'town'], name='marketplace_matched_1b0314_idx'), models.Index(fields=['created_at'], name='marketplace_created_186bad_idx')],
            },
        ),
    ]
